//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class PlatformSettings
{

    private PlatformSettingsHost[] hostsField;

    private PlatformSettingsHostInstance[] hostInstancesField;

    private PlatformSettingsAdapter[] adaptersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Host", IsNullable = false)]
    public PlatformSettingsHost[] Hosts
    {
        get
        {
            return this.hostsField;
        }
        set
        {
            this.hostsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("HostInstance", IsNullable = false)]
    public PlatformSettingsHostInstance[] HostInstances
    {
        get
        {
            return this.hostInstancesField;
        }
        set
        {
            this.hostInstancesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Adapter", IsNullable = false)]
    public PlatformSettingsAdapter[] Adapters
    {
        get
        {
            return this.adaptersField;
        }
        set
        {
            this.adaptersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class PlatformSettingsHost
{

    private string hostnameField;

    private string ntgroupnameField;

    private bool isdefaultField;

    private bool hosttrackingField;

    private bool authtrustedField;

    private string hosttypeField;

    private bool ishost32bitonlyField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hostname
    {
        get
        {
            return this.hostnameField;
        }
        set
        {
            this.hostnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ntgroupname
    {
        get
        {
            return this.ntgroupnameField;
        }
        set
        {
            this.ntgroupnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isdefault
    {
        get
        {
            return this.isdefaultField;
        }
        set
        {
            this.isdefaultField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hosttracking
    {
        get
        {
            return this.hosttrackingField;
        }
        set
        {
            this.hosttrackingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool authtrusted
    {
        get
        {
            return this.authtrustedField;
        }
        set
        {
            this.authtrustedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hosttype
    {
        get
        {
            return this.hosttypeField;
        }
        set
        {
            this.hosttypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ishost32bitonly
    {
        get
        {
            return this.ishost32bitonlyField;
        }
        set
        {
            this.ishost32bitonlyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class PlatformSettingsHostInstance
{

    private string servernameField;

    private string hostnameField;

    private string usernameField;

    private string passwordField;

    private bool startinstanceField;

    private bool isdisabledField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string servername
    {
        get
        {
            return this.servernameField;
        }
        set
        {
            this.servernameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hostname
    {
        get
        {
            return this.hostnameField;
        }
        set
        {
            this.hostnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username
    {
        get
        {
            return this.usernameField;
        }
        set
        {
            this.usernameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool startinstance
    {
        get
        {
            return this.startinstanceField;
        }
        set
        {
            this.startinstanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isdisabled
    {
        get
        {
            return this.isdisabledField;
        }
        set
        {
            this.isdisabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class PlatformSettingsAdapter
{

    private object[] itemsField;

    private string nameField;

    private string typeField;

    private string commentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReceiveHandler", typeof(PlatformSettingsAdapterReceiveHandler))]
    [System.Xml.Serialization.XmlElementAttribute("SendHandler", typeof(PlatformSettingsAdapterSendHandler))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class PlatformSettingsAdapterReceiveHandler
{

    private string hostnameField;

    private string configField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hostname
    {
        get
        {
            return this.hostnameField;
        }
        set
        {
            this.hostnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string config
    {
        get
        {
            return this.configField;
        }
        set
        {
            this.configField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class PlatformSettingsAdapterSendHandler
{

    private string hostnameField;

    private string configField;

    private bool isdefaultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hostname
    {
        get
        {
            return this.hostnameField;
        }
        set
        {
            this.hostnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string config
    {
        get
        {
            return this.configField;
        }
        set
        {
            this.configField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isdefault
    {
        get
        {
            return this.isdefaultField;
        }
        set
        {
            this.isdefaultField = value;
        }
    }
}
